name: GETA
version: 2.1.0
main: be.th3controller.geta.GETA
permissions:
    geta.friendly:
      description: Allows to egg all friendly mobs
      children:
        geta.bat: true
        geta.chicken: true
        geta.mooshroom: true
        geta.ocelot: true
        geta.pig: true
        geta.sheep: true
        geta.squid: true
        geta.villager: true
    geta.neutral:
      description: Allows to egg all neutral mobs
      children:
        geta.enderman: true
        geta.wolf: true
        geta.pigzombie: true
    geta.hostile:
      description: Allows to egg all hostile mobs
      children:
        geta.blaze: true
        geta.cavespider: true
        geta.creeper: true
        geta.ghast: true
        geta.magmacube: true
        geta.silverfish: true
        geta.skeleton: true
        geta.slime: true
        geta.spider: true
        geta.witch: true
        geta.zombie: true
    geta.bat:
      default: op
    geta.chicken:
      default: op
    geta.mooshroom:
      default: op
    geta.ocelot:
      default: op
    geta.pig:
      default: op
    geta.sheep:
      default: op
    geta.squid:
      default: op
    geta.villager:
      default: op
    geta.enderman:
      default: op
    geta.wolf:
      default: op
    geta.pigzombie:
      default: op
    geta.blaze:
      default: op
    geta.cavespider:
      default: op
    geta.creeper:
      default: op
    geta.ghast:
      default: op
    geta.magmacube:
      default: op
    geta.silverfish:
      default: op
    geta.skeleton:
      default: op
    geta.slime:
      default: op
    geta.spider:
      default: op
    geta.witch:
      default: op
    geta.zombie:
      default: op
commands:
   geta:
      description: Displays version number of GETA
      usage: /<command>
      aliases: gottaeggthemall
      permission: geta.version
      permission-message: You don't have insufficient permissions to do this command.